### ISSUE TITLE
RJ

### ISSUE THREAD

**Issue by KingdomCS** [Dark-Existed/MentoHUST-FZU-OpenWrt#1]
大佬这个仓库目前是可用的吗？试过minieap吗？

**Comment by Dark-Existed** [comment]
> 大佬这个仓库目前是可用的吗？试过minieap吗？

1. mentohust 和 minieap 都是模拟 linux 客户管 需要能使用 Linux 客户端才行 改改EAP也不行 checkv4是来自Linux客户端的
2. 直接联系网管让他给你开 Linux 客户端权限 
3. mentohust 代理模式可用
