### ISSUE TITLE
关于Linux权限

### ISSUE THREAD

**Issue by everypath** [Dark-Existed/MentoHUST-FZU-OpenWrt#2]
大佬，那只要去学校开通Linux权限就能继续使用mentohust 和 minieap了吗

**Comment by Dark-Existed** [comment]
> 大佬，那只要去学校开通Linux权限就能继续使用mentohust 和 minieap了吗

是的

**Comment by wxyttty** [comment]
是去联通营业厅吗

**Comment by everypath** [comment]
> 
> 
> 是去联通营业厅吗

好像生活区有个专门管校园网的技术中心吧

**Comment by Dark-Existed** [comment]
> 是去联通营业厅吗

有负责校园网的网络运维的网管 与联通营业厅无关

**Comment by taizhoujin** [comment]
> > 是去联通营业厅吗
> 
> 有负责校园网的网络运维的网管 与联通营业厅无关

已经联系校园网运维了，正在等回复，请问mentohust怎么设置啊，用的padavan系统的路由器，除了心跳间隔设置为0，其他的都跟之前一样吗？RuiJie版本要写6.86吗？

**Comment by everypath** [comment]
同问设置，运维已经给我开通了。同问怎么设置？还需要重新抓包吗
（在用mentohust的windows客户端（抓包工具和认证工具）时依旧显示密码错误

**Comment by everypath** [comment]
运维已经给我开通了。pandavan系统路由器同问怎么设置？还需要重新抓包吗？账号密码是填学号密码还是以前的锐捷账号密码
（在用mentohust的windows客户端（那个抓包工具和认证工具）时依旧显示密码错误

**Comment by LanYanY** [comment]
> 运维已经给我开通了。pandavan系统路由器同问怎么设置？还需要重新抓包吗？账号密码是填学号密码还是以前的锐捷账号密码
> （在用mentohust的windows客户端（那个抓包工具和认证工具）时依旧显示密码错误


一样，不知如何解决

**Comment by Dark-Existed** [comment]
> > 运维已经给我开通了。pandavan系统路由器同问怎么设置？还需要重新抓包吗？账号密码是填学号密码还是以前的锐捷账号密码
> > （在用mentohust的windows客户端（那个抓包工具和认证工具）时依旧显示密码错误
> 
> 
> 一样，不知如何解决

试一下SYSU版本的mentohust或者minieap他们的checkv4与我们学校的相同

**Comment by wxyttty** [comment]
报错用户不允许使用本服务

**Comment by Dark-Existed** [comment]
> 报错用户不允许使用本服务

minieap的话 --service 设置为 default

**Comment by wxyttty** [comment]
是mentohust

**Comment by wxyttty** [comment]
minieap可以

**Comment by Dark-Existed** [comment]
> 是mentohust

那就是你用的那一版 mentohust 中 service 没有改过来  
用能用的就好

**Comment by everypath** [comment]
> minieap可以

求私教学（捂脸），非计算机学生看了许多教程还是不太懂

**Comment by wxyttty** [comment]
> > minieap可以
> 
> 求私教学（捂脸），非计算机学生看了许多教程还是不太懂

用minieap就好了 不用sysu的也可以认证

**Comment by Dark-Existed** [comment]
> > minieap可以
> 
> 求私教学（捂脸），非计算机学生看了许多教程还是不太懂

readme里面的3条 都是可以实现的 1 要是搞不来 看看 2 和 3 
每一条都是一种可以通过认证的方法

**Comment by wxyttty** [comment]
3具体怎么操作

**Comment by Dark-Existed** [comment]
> 3具体怎么操作

改路由器MAC地址 在新系统网页上可以查询到
然后需要个交换机来骗过上面的交换机让它当你没拔过线

**Comment by everypath** [comment]
> 
> 
> > 3具体怎么操作
> 
> 改路由器MAC地址 在新系统网页上可以查询到
> 然后需要个交换机来骗过上面的交换机让它当你没拔过线

是说用电脑和复制了电脑Mac地址的路由器都连交换机上，电脑认证完，路由器的WiFi就能使用吗
