### ISSUE TITLE
大大大大大佬，FJNU支持吗？

### ISSUE THREAD

**Issue by whistle003** [Dark-Existed/MentoHUST-FZU-OpenWrt#3]
请问大佬，这个算法支持FJNU的锐捷认证吗？

**Comment by Dark-Existed** [comment]
> 请问大佬，这个算法支持FJNU的锐捷认证吗？

只能说你试试看 因为不确定你们那的版本 和 里面具体的参数是否一致
这个是模拟 Linux 客户端的 同时需要你们那允许使用 Linux 客户端才能用 

这学期我们这更换成网页认证了 变得更容易了 只要个脚本就行

**Comment by Dark-Existed** [comment]
实在不行 可以考虑这两个 不过没做过验证 原项目编译报错 做了点修改 让项目能编译起来

[mentohust-v4-proxy](https://github.com/Dark-Existed/mentohust-v4-proxy)
[mentohust-proxy](https://github.com/Dark-Existed/mentohust-proxy)

从原理出发这个是可以的 缺点就是 登录需要用到电脑 


要是认证服务器没有心跳包检测 也可以直接考虑 mac地址伪装 就好

**Comment by whistle003** [comment]
> 实在不行 可以考虑这两个 不过没做过验证 原项目编译报错 做了点修改 让项目能编译起来
> 
> [mentohust-v4-proxy](https://github.com/Dark-Existed/mentohust-v4-proxy) [mentohust-proxy](https://github.com/Dark-Existed/mentohust-proxy)
> 
> 从原理出发这个是可以的 缺点就是 登录需要用到电脑
> 
> 要是认证服务器没有心跳包检测 也可以直接考虑 mac地址伪装 就好

好的，多谢指导，我去试试
